// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYlwNY2eeWIozGRPzuP27_uHQ3B7jIMf4',
    appId: '1:743929925622:web:5d74c18edfdbf56e89c1d7',
    messagingSenderId: '743929925622',
    projectId: 'flutter-chatapp-5cb55',
    authDomain: 'flutter-chatapp-5cb55.firebaseapp.com',
    storageBucket: 'flutter-chatapp-5cb55.firebasestorage.app',
    measurementId: 'G-FX6S6Y7D23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXCJ9SLRrqj7r1sIiNlPoxgQz0hEsF0o',
    appId: '1:743929925622:android:17b4c44448b4efcf89c1d7',
    messagingSenderId: '743929925622',
    projectId: 'flutter-chatapp-5cb55',
    storageBucket: 'flutter-chatapp-5cb55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCRDstSCUN-5aTAbR_IEk7B3DpYmTkYw',
    appId: '1:743929925622:ios:8c6f4645f99d365089c1d7',
    messagingSenderId: '743929925622',
    projectId: 'flutter-chatapp-5cb55',
    storageBucket: 'flutter-chatapp-5cb55.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgCRDstSCUN-5aTAbR_IEk7B3DpYmTkYw',
    appId: '1:743929925622:ios:8c6f4645f99d365089c1d7',
    messagingSenderId: '743929925622',
    projectId: 'flutter-chatapp-5cb55',
    storageBucket: 'flutter-chatapp-5cb55.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYlwNY2eeWIozGRPzuP27_uHQ3B7jIMf4',
    appId: '1:743929925622:web:60bc738497bf86ac89c1d7',
    messagingSenderId: '743929925622',
    projectId: 'flutter-chatapp-5cb55',
    authDomain: 'flutter-chatapp-5cb55.firebaseapp.com',
    storageBucket: 'flutter-chatapp-5cb55.firebasestorage.app',
    measurementId: 'G-7QKHC95MPR',
  );
}
