// lib/main.dart
import 'package:chat_app/core/theme/app_theme.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:remixicon/remixicon.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'firebase_options.dart'; // Generated by flutterfire configure
import 'providers/auth_provider.dart';
import 'core/features/chat/application/chat_provider.dart';
import 'core/features/chat/presentation/screens/auth_screen.dart';
import 'core/features/chat/presentation/screens/home_screen.dart';
import 'core/features/chat/presentation/screens/search_screen.dart';
import 'core/features/chat/presentation/screens/profile_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final prefs = await SharedPreferences.getInstance();
  final isLoggedIn = prefs.getString('userId') != null;
  runApp(MyApp(isLoggedIn: isLoggedIn));
}

class MyApp extends StatelessWidget {
  final bool isLoggedIn;
  const MyApp({required this.isLoggedIn, super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ChatProvider()),
      ],
      child: Builder(
        builder: (context) {
          final themeProvider = context.watch<ThemeProvider>();

          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Chat App',
            theme: lightTheme,
            darkTheme: darkTheme,
            themeMode: themeProvider.themeMode,
            home: isLoggedIn ? const BottomNavWrapper() : const AuthScreen(),
            routes: {
              '/auth': (_) => const AuthScreen(),
              '/search': (_) => const SearchScreen(),
              '/home': (_) => const HomeScreen(),
            },
          );
        },
      ),
    );
  }
}

class BottomNavWrapper extends StatefulWidget {
  const BottomNavWrapper({super.key});

  @override
  State<BottomNavWrapper> createState() => _BottomNavWrapperState();
}

class _BottomNavWrapperState extends State<BottomNavWrapper> {
  int _currentIndex = 0;

  final List<Widget> _tabs = const [HomeScreen(), ProfileScreen()];

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      body: IndexedStack(index: _currentIndex, children: _tabs),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        currentIndex: _currentIndex,
        backgroundColor: isDark
            ? const Color(0xFF050505)
            : theme.scaffoldBackgroundColor,
        selectedItemColor: theme.colorScheme.primary,
        unselectedItemColor: theme.textTheme.bodySmall?.color?.withOpacity(0.6),
        onTap: (index) => setState(() => _currentIndex = index),
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Remix.chat_1_line),
            activeIcon: Icon(Remix.chat_1_fill),
            label: 'Chats',
          ),
          BottomNavigationBarItem(
            icon: Icon(Remix.user_3_line),
            activeIcon: Icon(Remix.user_3_fill),
            label: 'Profile',
          ),
        ],
      ),
    );
  }
}
